/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.dobackaofront.controle_de_estoque.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Família Santos
 */
public class GuiControleDeEstoque extends javax.swing.JFrame {

    /**
     * Creates new form GuiControleDeEstoque
     */
    public GuiControleDeEstoque() {
        initComponents();
        jInternalFrameCadastroCategoria.setVisible(false);
        jInternalFrameCadastroItem.setVisible(false);
        jInternalFramePesquisarItem.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneControleDeEstoque = new javax.swing.JDesktopPane();
        jInternalFrameCadastroCategoria = new javax.swing.JInternalFrame();
        jLabelCadastroCategoriaNome = new javax.swing.JLabel();
        jTextFieldCadastroCategoriaNome = new javax.swing.JTextField();
        jButtonCadastroCategoriaSalvar = new javax.swing.JButton();
        jButtonCadastroCategoriaCancelar = new javax.swing.JButton();
        jInternalFramePesquisarItem = new javax.swing.JInternalFrame();
        jLabelPesquisarNome = new javax.swing.JLabel();
        jTextFieldPesquisarNome = new javax.swing.JTextField();
        jButtonPesquisarSalvar = new javax.swing.JButton();
        jButtonPesquisarCancelar = new javax.swing.JButton();
        jInternalFrameCadastroItem = new javax.swing.JInternalFrame();
        jLabelCadastroItemNome = new javax.swing.JLabel();
        jTextFieldCadastroItemNome = new javax.swing.JTextField();
        jLabelCadastroItemQuantidade = new javax.swing.JLabel();
        jTextFieldCadastroItemQuantidade = new javax.swing.JTextField();
        jLabelCadastroItemCategoria = new javax.swing.JLabel();
        jComboBoxCadastroItemCategoria = new javax.swing.JComboBox<>();
        jButtonCadastroItemSalvar = new javax.swing.JButton();
        jButtonCadastroItemCancelar = new javax.swing.JButton();
        jMenuBarControleDeEstoque = new javax.swing.JMenuBar();
        jMenuControleDeEstoqueCadastro = new javax.swing.JMenu();
        jMenuItemControleDeEstoqueCadastroCategoria = new javax.swing.JMenuItem();
        jMenuItemControleDeEstoqueCadastroItem = new javax.swing.JMenuItem();
        jMenuControleDeEstoqueEdicao = new javax.swing.JMenu();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesquisarCategoria = new javax.swing.JMenuItem();
        jMenuItemPesquisarItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Estoque");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPaneControleDeEstoque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrameCadastroCategoria.setTitle("Cadastro de Categoria");
        jInternalFrameCadastroCategoria.setMaximumSize(new java.awt.Dimension(350, 163));
        jInternalFrameCadastroCategoria.setMinimumSize(new java.awt.Dimension(350, 163));
        jInternalFrameCadastroCategoria.setPreferredSize(new java.awt.Dimension(350, 163));
        jInternalFrameCadastroCategoria.setVisible(true);
        jInternalFrameCadastroCategoria.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCadastroCategoriaNome.setText("Nome da Categoria:");
        jInternalFrameCadastroCategoria.getContentPane().add(jLabelCadastroCategoriaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jInternalFrameCadastroCategoria.getContentPane().add(jTextFieldCadastroCategoriaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 189, -1));

        jButtonCadastroCategoriaSalvar.setText("Salvar");
        jButtonCadastroCategoriaSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCategoriaSalvarActionPerformed(evt);
            }
        });
        jInternalFrameCadastroCategoria.getContentPane().add(jButtonCadastroCategoriaSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jButtonCadastroCategoriaCancelar.setText("Cancelar");
        jButtonCadastroCategoriaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCategoriaCancelarActionPerformed(evt);
            }
        });
        jInternalFrameCadastroCategoria.getContentPane().add(jButtonCadastroCategoriaCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jDesktopPaneControleDeEstoque.add(jInternalFrameCadastroCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 5, 350, 163));

        jInternalFramePesquisarItem.setTitle("Pesquisar Item");
        jInternalFramePesquisarItem.setMaximumSize(new java.awt.Dimension(430, 150));
        jInternalFramePesquisarItem.setMinimumSize(new java.awt.Dimension(430, 150));
        jInternalFramePesquisarItem.setPreferredSize(new java.awt.Dimension(430, 150));
        jInternalFramePesquisarItem.setVisible(true);
        jInternalFramePesquisarItem.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPesquisarNome.setText("Informe o Nome do Item:");
        jInternalFramePesquisarItem.getContentPane().add(jLabelPesquisarNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));
        jInternalFramePesquisarItem.getContentPane().add(jTextFieldPesquisarNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 6, 191, -1));

        jButtonPesquisarSalvar.setText("Pesquisar");
        jButtonPesquisarSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarSalvarActionPerformed(evt);
            }
        });
        jInternalFramePesquisarItem.getContentPane().add(jButtonPesquisarSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 71, -1, -1));

        jButtonPesquisarCancelar.setText("Cancelar");
        jButtonPesquisarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCancelarActionPerformed(evt);
            }
        });
        jInternalFramePesquisarItem.getContentPane().add(jButtonPesquisarCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 71, -1, -1));

        jDesktopPaneControleDeEstoque.add(jInternalFramePesquisarItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 430, 150));

        jInternalFrameCadastroItem.setTitle("Cadastro de Item");
        jInternalFrameCadastroItem.setMaximumSize(new java.awt.Dimension(300, 255));
        jInternalFrameCadastroItem.setMinimumSize(new java.awt.Dimension(300, 255));
        jInternalFrameCadastroItem.setPreferredSize(new java.awt.Dimension(300, 255));
        jInternalFrameCadastroItem.setVisible(true);
        jInternalFrameCadastroItem.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCadastroItemNome.setText("Nome do Item:");
        jInternalFrameCadastroItem.getContentPane().add(jLabelCadastroItemNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jInternalFrameCadastroItem.getContentPane().add(jTextFieldCadastroItemNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 154, -1));

        jLabelCadastroItemQuantidade.setText("Quantidade:");
        jInternalFrameCadastroItem.getContentPane().add(jLabelCadastroItemQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jInternalFrameCadastroItem.getContentPane().add(jTextFieldCadastroItemQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 98, -1));

        jLabelCadastroItemCategoria.setText("Categoria:");
        jInternalFrameCadastroItem.getContentPane().add(jLabelCadastroItemCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jComboBoxCadastroItemCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material de Expediente", "Material Hospitalar", "Material Permanente" }));
        jInternalFrameCadastroItem.getContentPane().add(jComboBoxCadastroItemCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jButtonCadastroItemSalvar.setText("Salvar");
        jButtonCadastroItemSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroItemSalvarActionPerformed(evt);
            }
        });
        jInternalFrameCadastroItem.getContentPane().add(jButtonCadastroItemSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jButtonCadastroItemCancelar.setText("Cancelar");
        jButtonCadastroItemCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroItemCancelarActionPerformed(evt);
            }
        });
        jInternalFrameCadastroItem.getContentPane().add(jButtonCadastroItemCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jDesktopPaneControleDeEstoque.add(jInternalFrameCadastroItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 300, 255));

        getContentPane().add(jDesktopPaneControleDeEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 600, 370));

        jMenuControleDeEstoqueCadastro.setText("Cadastro");

        jMenuItemControleDeEstoqueCadastroCategoria.setText("Categoria");
        jMenuItemControleDeEstoqueCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemControleDeEstoqueCadastroCategoriaActionPerformed(evt);
            }
        });
        jMenuControleDeEstoqueCadastro.add(jMenuItemControleDeEstoqueCadastroCategoria);

        jMenuItemControleDeEstoqueCadastroItem.setText("Item");
        jMenuItemControleDeEstoqueCadastroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemControleDeEstoqueCadastroItemActionPerformed(evt);
            }
        });
        jMenuControleDeEstoqueCadastro.add(jMenuItemControleDeEstoqueCadastroItem);

        jMenuBarControleDeEstoque.add(jMenuControleDeEstoqueCadastro);

        jMenuControleDeEstoqueEdicao.setText("Edição");
        jMenuBarControleDeEstoque.add(jMenuControleDeEstoqueEdicao);

        jMenuPesquisar.setText("Pesquisa");

        jMenuItemPesquisarCategoria.setText("Categoria");
        jMenuPesquisar.add(jMenuItemPesquisarCategoria);

        jMenuItemPesquisarItem.setText("Item");
        jMenuItemPesquisarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarItemActionPerformed(evt);
            }
        });
        jMenuPesquisar.add(jMenuItemPesquisarItem);

        jMenuBarControleDeEstoque.add(jMenuPesquisar);

        setJMenuBar(jMenuBarControleDeEstoque);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemControleDeEstoqueCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemControleDeEstoqueCadastroCategoriaActionPerformed
        // TODO add your handling code here:
        resetCadastroItem();
        jInternalFrameCadastroItem.setVisible(false);
        jTextFieldPesquisarNome.setText("");
        jInternalFramePesquisarItem.setVisible(false);
        jInternalFrameCadastroCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItemControleDeEstoqueCadastroCategoriaActionPerformed

    private void jMenuItemControleDeEstoqueCadastroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemControleDeEstoqueCadastroItemActionPerformed
        // TODO add your handling code here:
        jTextFieldCadastroCategoriaNome.setText("");
        jInternalFrameCadastroCategoria.setVisible(false);
        jTextFieldPesquisarNome.setText("");
        jInternalFramePesquisarItem.setVisible(false);
        jInternalFrameCadastroItem.setVisible(true);
    }//GEN-LAST:event_jMenuItemControleDeEstoqueCadastroItemActionPerformed

    private void jButtonCadastroCategoriaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCategoriaCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldCadastroCategoriaNome.setText("");
        jInternalFrameCadastroCategoria.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroCategoriaCancelarActionPerformed

    private void jButtonCadastroCategoriaSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCategoriaSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldCadastroCategoriaNome.getText();

        validarCadastroCategoria(nome);
    }//GEN-LAST:event_jButtonCadastroCategoriaSalvarActionPerformed

    private void jButtonCadastroItemCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroItemCancelarActionPerformed
        // TODO add your handling code here:
        resetCadastroItem();
        jInternalFrameCadastroItem.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroItemCancelarActionPerformed

    private void jButtonCadastroItemSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroItemSalvarActionPerformed
        validarCadastroItem();        
    }//GEN-LAST:event_jButtonCadastroItemSalvarActionPerformed

    private void jButtonPesquisarSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarSalvarActionPerformed
        // TODO add your handling code here:
        System.out.println("Estou Pesquisando!!!");
        jTextFieldPesquisarNome.setText("");
        jInternalFramePesquisarItem.setVisible(false);
    }//GEN-LAST:event_jButtonPesquisarSalvarActionPerformed

    private void jButtonPesquisarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldPesquisarNome.setText("");
        jInternalFramePesquisarItem.setVisible(false);
    }//GEN-LAST:event_jButtonPesquisarCancelarActionPerformed

    private void jMenuItemPesquisarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarItemActionPerformed
        // TODO add your handling code here:
        jTextFieldCadastroCategoriaNome.setText("");
        jInternalFrameCadastroCategoria.setVisible(false);
        resetCadastroItem();
        jInternalFrameCadastroItem.setVisible(false);
        jInternalFramePesquisarItem.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisarItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiControleDeEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiControleDeEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiControleDeEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiControleDeEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiControleDeEstoque().setVisible(true);
            }
        });
    }
    
    public void validarCadastroCategoria(String nome) {
        if (nome.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O campo Nome da Categoria está vazio!");
        } else {
            System.out.println("O Nome da categoria é: "+nome);
            JOptionPane.showMessageDialog(rootPane, "A Categoria: "+nome+" foi cadastrada com Sucesso!");
            jTextFieldCadastroCategoriaNome.setText("");
            jInternalFrameCadastroCategoria.setVisible(false);
        }
    }
    
    public void validarCadastroItem() {
        String nome = jTextFieldCadastroItemNome.getText();
        int quantidade;
        
        if(nome.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O campo Nome do Item está vazio!");
        } else {
            String quantAuxiliar = jTextFieldCadastroItemQuantidade.getText();
            
            if(quantAuxiliar.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "O campo Quantidade está vazio!");
            } else {
                try {
                    quantidade = Integer.parseInt(quantAuxiliar);
                               
                    String categoria = jComboBoxCadastroItemCategoria.getSelectedItem().toString();
                    System.out.println(nome+", "+quantidade+", "+categoria);

                    JOptionPane.showMessageDialog(rootPane, "O item "+nome+" foi cadastrado com Sucesso!");

                    jTextFieldCadastroItemNome.setText("");
                    jTextFieldCadastroItemQuantidade.setText("");
                    jComboBoxCadastroItemCategoria.setSelectedIndex(0);

                    jInternalFrameCadastroItem.setVisible(false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Insina no campo Quantidade apenas valores inteiros!");
                }    
            }
        }
    }
    
    public void resetCadastroItem() {
        jTextFieldCadastroItemNome.setText("");
        jTextFieldCadastroItemQuantidade.setText("");
        jComboBoxCadastroItemCategoria.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroCategoriaCancelar;
    private javax.swing.JButton jButtonCadastroCategoriaSalvar;
    private javax.swing.JButton jButtonCadastroItemCancelar;
    private javax.swing.JButton jButtonCadastroItemSalvar;
    private javax.swing.JButton jButtonPesquisarCancelar;
    private javax.swing.JButton jButtonPesquisarSalvar;
    private javax.swing.JComboBox<String> jComboBoxCadastroItemCategoria;
    private javax.swing.JDesktopPane jDesktopPaneControleDeEstoque;
    private javax.swing.JInternalFrame jInternalFrameCadastroCategoria;
    private javax.swing.JInternalFrame jInternalFrameCadastroItem;
    private javax.swing.JInternalFrame jInternalFramePesquisarItem;
    private javax.swing.JLabel jLabelCadastroCategoriaNome;
    private javax.swing.JLabel jLabelCadastroItemCategoria;
    private javax.swing.JLabel jLabelCadastroItemNome;
    private javax.swing.JLabel jLabelCadastroItemQuantidade;
    private javax.swing.JLabel jLabelPesquisarNome;
    private javax.swing.JMenuBar jMenuBarControleDeEstoque;
    private javax.swing.JMenu jMenuControleDeEstoqueCadastro;
    private javax.swing.JMenu jMenuControleDeEstoqueEdicao;
    private javax.swing.JMenuItem jMenuItemControleDeEstoqueCadastroCategoria;
    private javax.swing.JMenuItem jMenuItemControleDeEstoqueCadastroItem;
    private javax.swing.JMenuItem jMenuItemPesquisarCategoria;
    private javax.swing.JMenuItem jMenuItemPesquisarItem;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JTextField jTextFieldCadastroCategoriaNome;
    private javax.swing.JTextField jTextFieldCadastroItemNome;
    private javax.swing.JTextField jTextFieldCadastroItemQuantidade;
    private javax.swing.JTextField jTextFieldPesquisarNome;
    // End of variables declaration//GEN-END:variables
}
