/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.dobackaofront.controle_de_estoque.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Família Santos
 */
public class GuiControleDeEstoque extends javax.swing.JFrame {

    /**
     * Creates new form GuiControleDeEstoque
     */
    public GuiControleDeEstoque() {
        initComponents();
        jInternalFrameCadastroCategoria.setVisible(false);
        jInternalFrameCadastroItem.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneControleDeEstoque = new javax.swing.JDesktopPane();
        jInternalFrameCadastroItem = new javax.swing.JInternalFrame();
        jLabelCadastroItemNome = new javax.swing.JLabel();
        jTextFieldCadastroItemNome = new javax.swing.JTextField();
        jLabelCadastroItemQuantidade = new javax.swing.JLabel();
        jTextFieldCadastroItemQuantidade = new javax.swing.JTextField();
        jLabelCadastroItemCategoria = new javax.swing.JLabel();
        jComboBoxCadastroItemCategoria = new javax.swing.JComboBox<>();
        jButtonCadastroItemSalvar = new javax.swing.JButton();
        jButtonCadastroItemCancelar = new javax.swing.JButton();
        jInternalFrameCadastroCategoria = new javax.swing.JInternalFrame();
        jLabelCadastroCategoriaNome = new javax.swing.JLabel();
        jTextFieldCadastroCategoriaNome = new javax.swing.JTextField();
        jButtonCadastroCategoriaSalvar = new javax.swing.JButton();
        jButtonCadastroCategoriaCancelar = new javax.swing.JButton();
        jMenuBarControleDeEstoque = new javax.swing.JMenuBar();
        jMenuControleDeEstoqueCadastro = new javax.swing.JMenu();
        jMenuItemControleDeEstoqueCadastroCategoria = new javax.swing.JMenuItem();
        jMenuItemControleDeEstoqueCadastroItem = new javax.swing.JMenuItem();
        jMenuControleDeEstoqueEdicao = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Estoque");
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jInternalFrameCadastroItem.setTitle("Cadastro de Item");
        jInternalFrameCadastroItem.setMaximumSize(new java.awt.Dimension(594, 306));
        jInternalFrameCadastroItem.setMinimumSize(new java.awt.Dimension(594, 306));
        jInternalFrameCadastroItem.setVisible(true);

        jLabelCadastroItemNome.setText("Nome do Item:");

        jLabelCadastroItemQuantidade.setText("Quantidade:");

        jLabelCadastroItemCategoria.setText("Categoria:");

        jComboBoxCadastroItemCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material de Expediente", "Material Hospitalar", "Material Permanente" }));

        jButtonCadastroItemSalvar.setText("Salvar");
        jButtonCadastroItemSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroItemSalvarActionPerformed(evt);
            }
        });

        jButtonCadastroItemCancelar.setText("Cancelar");
        jButtonCadastroItemCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroItemCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCadastroItemLayout = new javax.swing.GroupLayout(jInternalFrameCadastroItem.getContentPane());
        jInternalFrameCadastroItem.getContentPane().setLayout(jInternalFrameCadastroItemLayout);
        jInternalFrameCadastroItemLayout.setHorizontalGroup(
            jInternalFrameCadastroItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastroItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastroItemNome)
                    .addComponent(jLabelCadastroItemQuantidade)
                    .addComponent(jLabelCadastroItemCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameCadastroItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCadastroItemNome)
                    .addComponent(jTextFieldCadastroItemQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCadastroItemCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(330, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastroItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadastroItemSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCadastroItemCancelar)
                .addGap(21, 21, 21))
        );
        jInternalFrameCadastroItemLayout.setVerticalGroup(
            jInternalFrameCadastroItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastroItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCadastroItemNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroItemNome))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroItemQuantidade)
                    .addComponent(jTextFieldCadastroItemQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroItemCategoria)
                    .addComponent(jComboBoxCadastroItemCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(jInternalFrameCadastroItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroItemSalvar)
                    .addComponent(jButtonCadastroItemCancelar))
                .addContainerGap())
        );

        jInternalFrameCadastroCategoria.setTitle("Cadastro de Categoria");
        jInternalFrameCadastroCategoria.setMaximumSize(new java.awt.Dimension(588, 233));
        jInternalFrameCadastroCategoria.setMinimumSize(new java.awt.Dimension(588, 233));
        jInternalFrameCadastroCategoria.setVisible(true);

        jLabelCadastroCategoriaNome.setText("Nome da Categoria:");

        jButtonCadastroCategoriaSalvar.setText("Salvar");
        jButtonCadastroCategoriaSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCategoriaSalvarActionPerformed(evt);
            }
        });

        jButtonCadastroCategoriaCancelar.setText("Cancelar");
        jButtonCadastroCategoriaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCategoriaCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCadastroCategoriaLayout = new javax.swing.GroupLayout(jInternalFrameCadastroCategoria.getContentPane());
        jInternalFrameCadastroCategoria.getContentPane().setLayout(jInternalFrameCadastroCategoriaLayout);
        jInternalFrameCadastroCategoriaLayout.setHorizontalGroup(
            jInternalFrameCadastroCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastroCategoriaNome)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCadastroCategoriaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButtonCadastroCategoriaSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCadastroCategoriaCancelar))
        );
        jInternalFrameCadastroCategoriaLayout.setVerticalGroup(
            jInternalFrameCadastroCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroCategoriaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jInternalFrameCadastroCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroCategoriaNome)
                    .addComponent(jTextFieldCadastroCategoriaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jInternalFrameCadastroCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroCategoriaSalvar)
                    .addComponent(jButtonCadastroCategoriaCancelar))
                .addContainerGap())
        );

        jDesktopPaneControleDeEstoque.setLayer(jInternalFrameCadastroItem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneControleDeEstoque.setLayer(jInternalFrameCadastroCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneControleDeEstoqueLayout = new javax.swing.GroupLayout(jDesktopPaneControleDeEstoque);
        jDesktopPaneControleDeEstoque.setLayout(jDesktopPaneControleDeEstoqueLayout);
        jDesktopPaneControleDeEstoqueLayout.setHorizontalGroup(
            jDesktopPaneControleDeEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneControleDeEstoqueLayout.createSequentialGroup()
                .addGroup(jDesktopPaneControleDeEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneControleDeEstoqueLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jInternalFrameCadastroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jInternalFrameCadastroItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jDesktopPaneControleDeEstoqueLayout.setVerticalGroup(
            jDesktopPaneControleDeEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneControleDeEstoqueLayout.createSequentialGroup()
                .addComponent(jInternalFrameCadastroItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrameCadastroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuControleDeEstoqueCadastro.setText("Cadastro");

        jMenuItemControleDeEstoqueCadastroCategoria.setText("Categoria");
        jMenuItemControleDeEstoqueCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemControleDeEstoqueCadastroCategoriaActionPerformed(evt);
            }
        });
        jMenuControleDeEstoqueCadastro.add(jMenuItemControleDeEstoqueCadastroCategoria);

        jMenuItemControleDeEstoqueCadastroItem.setText("Item");
        jMenuItemControleDeEstoqueCadastroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemControleDeEstoqueCadastroItemActionPerformed(evt);
            }
        });
        jMenuControleDeEstoqueCadastro.add(jMenuItemControleDeEstoqueCadastroItem);

        jMenuBarControleDeEstoque.add(jMenuControleDeEstoqueCadastro);

        jMenuControleDeEstoqueEdicao.setText("Edição");
        jMenuBarControleDeEstoque.add(jMenuControleDeEstoqueEdicao);

        setJMenuBar(jMenuBarControleDeEstoque);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneControleDeEstoque)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneControleDeEstoque)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemControleDeEstoqueCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemControleDeEstoqueCadastroCategoriaActionPerformed
        // TODO add your handling code here:
        jInternalFrameCadastroCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItemControleDeEstoqueCadastroCategoriaActionPerformed

    private void jMenuItemControleDeEstoqueCadastroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemControleDeEstoqueCadastroItemActionPerformed
        // TODO add your handling code here:
        jInternalFrameCadastroItem.setVisible(true);
    }//GEN-LAST:event_jMenuItemControleDeEstoqueCadastroItemActionPerformed

    private void jButtonCadastroCategoriaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCategoriaCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldCadastroCategoriaNome.setText("");
        jInternalFrameCadastroCategoria.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroCategoriaCancelarActionPerformed

    private void jButtonCadastroCategoriaSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCategoriaSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldCadastroCategoriaNome.getText();

        validarCadastroCategoria(nome);
    }//GEN-LAST:event_jButtonCadastroCategoriaSalvarActionPerformed

    private void jButtonCadastroItemCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroItemCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldCadastroItemNome.setText("");
        jTextFieldCadastroItemQuantidade.setText("");
        jComboBoxCadastroItemCategoria.setSelectedIndex(0);
        jInternalFrameCadastroItem.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroItemCancelarActionPerformed

    private void jButtonCadastroItemSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroItemSalvarActionPerformed
        String nome = jTextFieldCadastroItemNome.getText();
        int quantidade;
        
        if(nome.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O campo Nome do Item está vazio!");
        } else {
            String quantAuxiliar = jTextFieldCadastroItemQuantidade.getText();
            
            if(quantAuxiliar.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "O campo Quantidade está vazio!");
            } else {
                try {
                    quantidade = Integer.parseInt(quantAuxiliar);
                               
                    String categoria = jComboBoxCadastroItemCategoria.getSelectedItem().toString();
                    System.out.println(nome+", "+quantidade+", "+categoria);

                    JOptionPane.showMessageDialog(rootPane, "O item "+nome+" foi cadastrado com Sucesso!");

                    jTextFieldCadastroItemNome.setText("");
                    jTextFieldCadastroItemQuantidade.setText("");
                    jComboBoxCadastroItemCategoria.setSelectedIndex(0);

                    jInternalFrameCadastroItem.setVisible(false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Insina no campo Quantidade apenas valores inteiros!");
                }    
            }
        }
    }//GEN-LAST:event_jButtonCadastroItemSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiControleDeEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiControleDeEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiControleDeEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiControleDeEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiControleDeEstoque().setVisible(true);
            }
        });
    }
    
    public void validarCadastroCategoria(String nome) {
        if (nome.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O campo Nome da Categoria está vazio!");
        } else {
            System.out.println("O Nome da categoria é: "+nome);
            JOptionPane.showMessageDialog(rootPane, "A Categoria: "+nome+" foi cadastrada com Sucesso!");
            jTextFieldCadastroCategoriaNome.setText("");
            jInternalFrameCadastroCategoria.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroCategoriaCancelar;
    private javax.swing.JButton jButtonCadastroCategoriaSalvar;
    private javax.swing.JButton jButtonCadastroItemCancelar;
    private javax.swing.JButton jButtonCadastroItemSalvar;
    private javax.swing.JComboBox<String> jComboBoxCadastroItemCategoria;
    private javax.swing.JDesktopPane jDesktopPaneControleDeEstoque;
    private javax.swing.JInternalFrame jInternalFrameCadastroCategoria;
    private javax.swing.JInternalFrame jInternalFrameCadastroItem;
    private javax.swing.JLabel jLabelCadastroCategoriaNome;
    private javax.swing.JLabel jLabelCadastroItemCategoria;
    private javax.swing.JLabel jLabelCadastroItemNome;
    private javax.swing.JLabel jLabelCadastroItemQuantidade;
    private javax.swing.JMenuBar jMenuBarControleDeEstoque;
    private javax.swing.JMenu jMenuControleDeEstoqueCadastro;
    private javax.swing.JMenu jMenuControleDeEstoqueEdicao;
    private javax.swing.JMenuItem jMenuItemControleDeEstoqueCadastroCategoria;
    private javax.swing.JMenuItem jMenuItemControleDeEstoqueCadastroItem;
    private javax.swing.JTextField jTextFieldCadastroCategoriaNome;
    private javax.swing.JTextField jTextFieldCadastroItemNome;
    private javax.swing.JTextField jTextFieldCadastroItemQuantidade;
    // End of variables declaration//GEN-END:variables
}
